### ISSUE TITLE
Not all items in the origin are transferred to the transfer user

### ISSUE THREAD

**Issue by JHendrickson4** [Esri-Private-Sector-SEs/gbd-migration#15]
this section does not seem to transfer all the participating items - it only transfers the item id specified in the global section.    

missing switching the owner of maps, layers, etc. 

 # reassign item to origin transfer user
    if item_origin.owner != ORIGIN_TRANSFER_USER:
        item_origin.reassign_to(ORIGIN_TRANSFER_USER)

**Comment by rfreedBusiness** [comment]
Closing this issue as this functionality has been added.
