### ISSUE TITLE
StoryMap was migrated but participating content was not

### ISSUE THREAD

**Issue by JHendrickson4** [Esri-Private-Sector-SEs/gbd-migration#16]
ITEM_ID = "57290822f66b4844b5950bc1425ec1d6"

Performing Web Content transfer for the following items: 
Freight Flow Visualization
Item(s) cloned successfully. Updating tags ... 
Web Content Transfer complete.

migrated item = 'be062ba3d3f64358932584babb817c0f'

**Comment by rfreedBusiness** [comment]
Need to add this functionality (still using a modified workflow from developer page). I'll get to this after bootcamp but should be similar to other items.
