### ISSUE TITLE
Update dictionary to include the actual service URL

### ISSUE THREAD

**Issue by JHendrickson4** [Esri-Private-Sector-SEs/gbd-migration#19]
Update the dictionary for the catalog so that it doesn't just return the 'homepage' which is only the item details. The  "URL": item.url will be more helpful in see where the services is actually coming from. See below:

`        d = {"Item Name": item.title, "Author": item.owner, "Sharing": item_share, "Description": item.description, "Item ID": item.id, "Groups": item.shared_with['groups'],
                            "Date Updated": last_edit, "URL": item.url, "Details Page": item.homepage,"Type": item.type, "Folder": fldr_name, "Tags": item.tags, "Categories": item.categories, 
                            "Content Status": item.content_status, "Related Items": related_ids, "Delete Protection": deletion_status, "Transfer Status": xfer}`

**Comment by rfreedBusiness** [comment]
Feeature added 9/18.
